export const APP_LOG_IN = 'APP_LOG_IN';
export const APP_LOGGED_IN = 'APP_LOGGED_IN';
export const APP_LOGGED_OUT = 'APP_LOGGED_OUT';
export const APP_LOADING_DONE = 'APP_LOADING_DONE';
export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_ACQUIRE_SESSION = 'APP_ACQUIRE_SESSION';
export const APP_ACQUIRE_SESSION_FULFILLED = 'APP_ACQUIRE_SESSION_FULFILLED';
export const APP_USER_LOGOUT = 'APP_USER_LOGOUT';